language: php

php:
  - '7.4'

services:
  - mysql

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=slim4_api_skeleton
    - DB_USER=root
    - DB_PASS=

before_install:
  - mysql -e 'CREATE DATABASE slim4_api_skeleton'

before_script:
- composer install -n

script:
- vendor/bin/phpunit
